export * from './account.service';
import { AccountService } from './account.service';
export * from './brands.service';
import { BrandsService } from './brands.service';
export * from './default.service';
import { DefaultService } from './default.service';
export * from './employee.service';
import { EmployeeService } from './employee.service';
export * from './inventoryRecord.service';
import { InventoryRecordService } from './inventoryRecord.service';
export * from './item.service';
import { ItemService } from './item.service';
export * from './position.service';
import { PositionService } from './position.service';
export * from './role.service';
import { RoleService } from './role.service';
export * from './software.service';
import { SoftwareService } from './software.service';
export * from './title.service';
import { TitleService } from './title.service';
export * from './typeOfItem.service';
import { TypeOfItemService } from './typeOfItem.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [AccountService, BrandsService, DefaultService, EmployeeService, InventoryRecordService, ItemService, PositionService, RoleService, SoftwareService, TitleService, TypeOfItemService, UserService];
